import AppKit
@testable import FloxBoxCore
import XCTest

final class ClipboardTextInserterTests: XCTestCase {
    func testInsertWritesTextAndRestoresWhenUnchanged() {
        let original = makePasteboardItem(string: "original")
        let pasteboard = TestPasteboard(items: [original])
        let commandV = TestCommandVPaster(success: true)
        var scheduled: (() -> Void)?

        let inserter = ClipboardTextInserter(
            pasteboardProvider: { pasteboard },
            commandVPaster: commandV,
            restoreDelay: 0,
            restoreScheduler: { _, work in scheduled = work },
            sourceIdentifier: "com.test",
        )

        XCTAssertTrue(inserter.insert(text: "hello"))
        XCTAssertEqual(commandV.callCount, 1)
        XCTAssertEqual(pasteboard.stringValue, "hello")
        XCTAssertTrue(pasteboard.containsType("org.nspasteboard.TransientType"))
        XCTAssertTrue(pasteboard.containsType("org.nspasteboard.AutoGeneratedType"))
        XCTAssertEqual(pasteboard.stringValue(forType: "org.nspasteboard.source"), "com.test")

        scheduled?()
        XCTAssertEqual(pasteboard.stringValue, "original")
    }

    func testInsertSkipsRestoreWhenClipboardChanges() {
        let original = makePasteboardItem(string: "original")
        let pasteboard = TestPasteboard(items: [original])
        let commandV = TestCommandVPaster(success: true)
        var scheduled: (() -> Void)?

        let inserter = ClipboardTextInserter(
            pasteboardProvider: { pasteboard },
            commandVPaster: commandV,
            restoreDelay: 0,
            restoreScheduler: { _, work in scheduled = work },
            sourceIdentifier: "com.test",
        )

        XCTAssertTrue(inserter.insert(text: "hello"))
        pasteboard.replace(with: makePasteboardItem(string: "user"))
        scheduled?()

        XCTAssertEqual(pasteboard.stringValue, "user")
    }

    func testInsertRestoresImmediatelyWhenPasteFails() {
        let original = makePasteboardItem(string: "original")
        let pasteboard = TestPasteboard(items: [original])
        let commandV = TestCommandVPaster(success: false)

        let inserter = ClipboardTextInserter(
            pasteboardProvider: { pasteboard },
            commandVPaster: commandV,
            restoreDelay: 0,
            restoreScheduler: { _, _ in XCTFail("restore should be immediate") },
            sourceIdentifier: "com.test",
        )

        XCTAssertFalse(inserter.insert(text: "hello"))
        XCTAssertEqual(pasteboard.stringValue, "original")
    }

    func testInsertLogsPasteAndRestoreWhenPasteFails() {
        let pasteboard = TestPasteboard(items: [])
        var logs: [String] = []

        let inserter = ClipboardTextInserter(
            pasteboardProvider: { pasteboard },
            commandVPaster: TestCommandVPaster(success: false),
            restoreDelay: 0,
            restoreScheduler: { _, work in work() },
            logger: { logs.append($0) },
        )

        _ = inserter.insert(text: "Hello")

        XCTAssertTrue(logs.contains { $0.contains("clipboard.insert.start") })
        XCTAssertTrue(logs.contains { $0.contains("clipboard.insert.commandV result=false") })
        XCTAssertTrue(logs.contains { $0.contains("clipboard.restore.immediate") })
    }

    func testRestoreUsesClonedItems() {
        let original = makePasteboardItem(string: "original")
        let pasteboard = TestPasteboard(items: [original])
        let commandV = TestCommandVPaster(success: true)
        var scheduled: (() -> Void)?

        let inserter = ClipboardTextInserter(
            pasteboardProvider: { pasteboard },
            commandVPaster: commandV,
            restoreDelay: 0,
            restoreScheduler: { _, work in scheduled = work },
            sourceIdentifier: "com.test",
        )

        XCTAssertTrue(inserter.insert(text: "hello"))
        scheduled?()

        XCTAssertFalse(pasteboard.attemptedOriginalRestore)
    }
}

private final class TestPasteboard: PasteboardAccessing {
    private(set) var changeCount: Int = 0
    private var items: [NSPasteboardItem]
    private let originalItemIDs: Set<ObjectIdentifier>
    private(set) var attemptedOriginalRestore = false

    init(items: [NSPasteboardItem]) {
        self.items = items
        originalItemIDs = Set(items.map { ObjectIdentifier($0) })
    }

    var pasteboardItems: [NSPasteboardItem]? { items }

    @discardableResult
    func clearContents() -> Int {
        items = []
        changeCount += 1
        return changeCount
    }

    @discardableResult
    func writeObjects(_ objects: [NSPasteboardWriting]) -> Bool {
        let newItems = objects.compactMap { $0 as? NSPasteboardItem }
        guard newItems.count == objects.count else { return false }
        if items.isEmpty,
           newItems.contains(where: { originalItemIDs.contains(ObjectIdentifier($0)) })
        {
            attemptedOriginalRestore = true
        }
        items = newItems
        changeCount += 1
        return true
    }

    func replace(with item: NSPasteboardItem) {
        items = [item]
        changeCount += 1
    }

    var stringValue: String? {
        items.first?.string(forType: .string)
    }

    func stringValue(forType type: String) -> String? {
        items.first?.string(forType: NSPasteboard.PasteboardType(type))
    }

    func containsType(_ type: String) -> Bool {
        items.first?.types.contains(NSPasteboard.PasteboardType(type)) == true
    }
}

private func makePasteboardItem(string: String) -> NSPasteboardItem {
    let item = NSPasteboardItem()
    item.setString(string, forType: .string)
    return item
}

private final class TestCommandVPaster: CommandVPasting {
    let success: Bool
    private(set) var callCount: Int = 0

    init(success: Bool) {
        self.success = success
    }

    func postCommandV() -> Bool {
        callCount += 1
        return success
    }
}
