disabled_rules:
  - opening_brace
  - closing_brace
  - indentation_width
  - statement_position
  - trailing_comma

opt_in_rules:
  - control_statement

line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 60
    error: 80
  allowed_symbols:
    - "_"
  validates_start_with_lowercase: false

file_length:
  warning: 1000
  error: 1200

type_body_length:
  warning: 1000
  error: 1200

function_body_length:
  warning: 120
  error: 200

force_cast:
  severity: warning

nesting:
  type_level: 2

included:
  - FloxBox
  - Packages
  - FloxBoxTests
  - FloxBoxUITests

excluded:
  - DerivedData
  - .build
  - .swiftpm
  - .venv
  - Packages/FloxBoxCore/.build
  - Packages/FloxBoxCore/.build/**
