import AppKit
import Carbon
import Foundation

public protocol PasteboardAccessing: AnyObject {
    var changeCount: Int { get }
    var pasteboardItems: [NSPasteboardItem]? { get }
    @discardableResult func clearContents() -> Int
    @discardableResult func writeObjects(_ objects: [NSPasteboardWriting]) -> Bool
}

extension NSPasteboard: PasteboardAccessing {}

public protocol CommandVPasting {
    func postCommandV() -> Bool
}

public struct CGEventCommandVPaster: CommandVPasting {
    public init() {}

    public func postCommandV() -> Bool {
        let keyCode = CGKeyCode(kVK_ANSI_V)
        guard let down = CGEvent(keyboardEventSource: nil, virtualKey: keyCode, keyDown: true),
              let up = CGEvent(keyboardEventSource: nil, virtualKey: keyCode, keyDown: false)
        else {
            return false
        }
        down.flags = .maskCommand
        up.flags = .maskCommand
        down.post(tap: .cghidEventTap)
        up.post(tap: .cghidEventTap)
        return true
    }
}

public final class ClipboardTextInserter: DictationTextInserting {
    private let pasteboardProvider: () -> PasteboardAccessing
    private var commandVPaster: CommandVPasting
    private let restoreDelay: TimeInterval
    private let restoreScheduler: (TimeInterval, @escaping () -> Void) -> Void
    private let sourceIdentifier: String

    public init(
        pasteboardProvider: @escaping () -> PasteboardAccessing = { NSPasteboard.general },
        commandVPaster: CommandVPasting = CGEventCommandVPaster(),
        restoreDelay: TimeInterval = 0.2,
        restoreScheduler: @escaping (TimeInterval, @escaping () -> Void) -> Void = { delay, work in
            DispatchQueue.main.asyncAfter(deadline: .now() + delay, execute: work)
        },
        sourceIdentifier: String = Bundle.main.bundleIdentifier ?? "FloxBox",
    ) {
        self.pasteboardProvider = pasteboardProvider
        self.commandVPaster = commandVPaster
        self.restoreDelay = restoreDelay
        self.restoreScheduler = restoreScheduler
        self.sourceIdentifier = sourceIdentifier
    }

    public func insert(text: String) -> Bool {
        guard !text.isEmpty else { return false }
        let pasteboard = pasteboardProvider()
        let originalItems = pasteboard.pasteboardItems ?? []

        let item = makePasteboardItem(text: text, source: sourceIdentifier)
        pasteboard.clearContents()
        guard pasteboard.writeObjects([item]) else { return false }
        let temporaryChangeCount = pasteboard.changeCount

        guard commandVPaster.postCommandV() else {
            restoreIfUnchanged(pasteboard: pasteboard, items: originalItems, changeCount: temporaryChangeCount)
            return false
        }

        restoreScheduler(restoreDelay) { [weak pasteboard] in
            guard let pasteboard else { return }
            self.restoreIfUnchanged(pasteboard: pasteboard, items: originalItems, changeCount: temporaryChangeCount)
        }
        return true
    }

    private func makePasteboardItem(text: String, source: String) -> NSPasteboardItem {
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
        item.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
        item.setString(source, forType: NSPasteboard.PasteboardType("org.nspasteboard.source"))
        return item
    }

    private func restoreIfUnchanged(
        pasteboard: PasteboardAccessing,
        items: [NSPasteboardItem],
        changeCount: Int,
    ) {
        guard pasteboard.changeCount == changeCount else { return }
        pasteboard.clearContents()
        if !items.isEmpty {
            _ = pasteboard.writeObjects(items)
        }
    }
}
